name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker credentials as environment variables
    - name: Set up Docker credentials
      env:
        DOCKER_USERNAME: "sangam01"
        DOCKER_PASSWORD: "dckr_pat_aldTuY7nODTZls4rRyP9cZl1iew"
      run: |
        echo $DOCKER_USERNAME
        echo $DOCKER_PASSWORD

    # Step 3: Log in to DockerHub using environment variables
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest
