name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for advanced builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    # Step 3: Log in to DockerHub using secrets for credentials
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Use secret for Docker access token

    # Step 4: Build and push Docker image using Buildx
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sangam01/fastapi-backend:latest
        builder: mybuilder  # Specify builder name
